{% set name = "rospo" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ferama/rospo/archive/v{{ version }}.tar.gz
  sha256: 9016ca7afacd107e5f330cac9827999cfb88ffd2c3c5750b1b20b4dc9441fbf3

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - rospo --help

about:
  home: https://github.com/ferama/rospo
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Simple, reliable, persistent ssh tunnels with embedded ssh server
  dev_url: https://github.com/ferama/rospo

extra:
  recipe-maintainers:
    - danielnachun
