{% set name = "rospo" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ferama/rospo/archive/v{{ version }}.tar.gz
  sha256: a0a8d60e0d4c0a93a0fe5e781809fcf9c12d278c2624123b2ae2dc9fabbd63e7

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - rospo --help

about:
  home: https://github.com/ferama/rospo
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Simple, reliable, persistent ssh tunnels with embedded ssh server
  dev_url: https://github.com/ferama/rospo

extra:
  recipe-maintainers:
    - danielnachun
