{% set name = "rospo" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ferama/rospo/archive/v{{ version }}.tar.gz
  sha256: 098c84c2c6904761065aeb7fdacdbd53b59fa12cc3d0368f1ca1712993323efa

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - rospo --help

about:
  home: https://github.com/ferama/rospo
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Simple, reliable, persistent ssh tunnels with embedded ssh server
  dev_url: https://github.com/ferama/rospo

extra:
  recipe-maintainers:
    - danielnachun
