schema_version: 1

context:
  version: "0.15.2"

package:
  name: rospo
  version: ${{ version }}

source:
  url: https://github.com/ferama/rospo/archive/v${{ version }}.tar.gz
  sha256: cc5595c5c7a378774a953f18b156579aa201cbe7589ab7f912e7028df434c3e6

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - rospo --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Simple, reliable, persistent ssh tunnels with embedded ssh server
  homepage: https://github.com/ferama/rospo
  repository: https://github.com/ferama/rospo

extra:
  recipe-maintainers:
    - danielnachun
