schema_version: 1

context:
  version: "0.15.3"

package:
  name: rospo
  version: ${{ version }}

source:
  url: https://github.com/ferama/rospo/archive/v${{ version }}.tar.gz
  sha256: 4c36291969c84159baff261841e6ccd9520e17f8bc9142bf815b9097322a8857

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - rospo --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Simple, reliable, persistent ssh tunnels with embedded ssh server
  homepage: https://github.com/ferama/rospo
  repository: https://github.com/ferama/rospo

extra:
  recipe-maintainers:
    - danielnachun
